const tvShowsActionTypes = {
  COMING_SOON_SHOWS: "COMING_SOON_SHOWS",
  TOP_RATED_SHOWS: "TOP_RATED_SHOWS",
  MOST_POPULAR_SHOWS: "MOST_POPULAR_SHOWS",

  NEXT_COMING_SOON_SHOWS: "NEXT_COMING_SOON_SHOWS",
  PREV_COMING_SOON_SHOWS: "PREV_COMING_SOON_SHOWS",

  START_LOADING_TOP_RATED_SHOWS: "START_LOADING_TOP_RATED_SHOWS",
  SUCCESS_LOADING_TOP_RATED_SHOWS: "SUCCESS_LOADING_TOP_RATED_SHOWS",
  FAILED_LOADING_TOP_RATED_SHOWS: "FAILED_LOADING_TOP_RATED_SHOWS",

  START_LOADING_MOST_POPULAR_SHOWS: "START_LOADING_MOST_POPULAR_SHOWS",
  SUCCESS_LOADING_MOST_POPULAR_SHOWS: "SUCCESS_LOADING_MOST_POPULAR_SHOWS",
  FAILED_LOADING_MOST_POPULAR_SHOWS: "FAILED_LOADING_MOST_POPULAR_SHOWS",
};

export default tvShowsActionTypes;
