const homepageActionTypes = {
  DISCOVERS: "DISCOVERS",
  FEATURES: "FEATURES",
  PEOPLE: "PEOPLE",
  TRENDINGS: "TRENDINGS",

  NEXT_DISCOVER: "NEXT_DISCOVER",
  PREV_DISCOVER: "PREV_DISCOVER",

  NEXT_FEATURE: "NEXT_FEATURE",
  NEXT_FEATURE_BY: "NEXT_FEATURE_BY",
  PREV_FEATURE: "PREV_FEATURE",
  PREV_FEATURE_BY: "PREV_FEATURE_BY",

  NEXT_PERSON: "NEXT_PERSON",
  NEXT_PERSON_BY: "NEXT_PERSON_BY",
  PREV_PERSON: "PREV_PERSON",
  PREV_PERSON_BY: "PREV_PERSON_BY",
};
export default homepageActionTypes;
